"""People Analytics Toolkit (people-analytics-toolkit).

A production-grade, mathematically rigorous framework implementing advanced
feature engineering techniques designed specifically for workforce intelligence,
human capital management (HCM), and People Analytics.

Modules:
- cardinality: Bayesian Target Encoding and Grouped LOO Z-Scores.
- memory: Fractional Differencing, Weighted Weeks Since, EWMA, EWMS, Double/Triple Smoothing, and Hazard Embeddings.
- chaos: Rolling Shannon Entropy, GARCH(1,1) Volatility, and Hawkes Intensity.
- anomalies: Autoencoder Reconstruction Error, KL Divergence, DTW, LCSS, EDR, and LOF.
- attribution: Log-Mean Decomposition (LMDI-I), LOO-ED, and SHAP Interactions.
- mobility: Career Movement Embeddings and Succession Planning.
- compensation: Compa-Ratio, Range Penetration, and Pay Band Classification.
"""

from people_analytics_toolkit._deprecation import (
    deprecated,
    deprecated_alias,
)
from people_analytics_toolkit.cardinality import (
    BayesianTargetEncoder,
    GroupedLOOZScore,
)
from people_analytics_toolkit.memory import (
    fractional_difference,
    get_fractional_weights,
    scan_fractional_differencing,
    weighted_weeks_since,
    calculate_ewma,
    compute_ewma,
    scan_ewma_spans,
    calculate_ewms,
    compute_ewms,
    calculate_poisson_ewma,
    compute_poisson_ewma,
    ExponentialSmoothingResult,
    SmoothingResult,
    double_exponential_smoothing,
    triple_exponential_smoothing,
    HazardEmbeddings,
    HazardEmbeddingTransformer,
    fit_hazard_embeddings,
    RollingMetricConfig,
    compute_rolling_metrics,
    calculate_rolling_metrics,
    RollingMetricsPipeline,
    singular_spectrum_analysis,
    compute_svd_smoothed_baseline,
    calculate_svd_smoothed_baseline,
    SingularSpectrumAnalysis,
    compute_lag_features,
    calculate_lag_features,
    compute_differencing_features,
    calculate_differencing_features,
    TemporalFeaturesPipeline,
)
from people_analytics_toolkit.chaos import (
    calculate_shannon_entropy,
    compute_shannon_entropy,
    rolling_shannon_entropy,
    GARCHVolatilityModel,
    GARCHVolatility,
    GARCHResult,
    GARCHModelResult,
    fit_garch_volatility,
    rolling_garch_volatility,
    HawkesProcessContagion,
    WorkforceHMMRegimes,
    WorkforceHMM,
    fit_workforce_hmm_regimes,
    calculate_bradford_score,
    compute_bradford_score,
    classify_bradford_risk,
    calculate_bradford_factor,
    compute_bradford_factor,
)
from people_analytics_toolkit.anomalies import (
    calculate_kl_divergence,
    compute_kl_divergence,
    calculate_jensen_shannon_divergence,
    compute_jensen_shannon_divergence,
    compute_dtw_distance,
    calculate_dtw_distance,
    compute_lcss_distance,
    calculate_lcss_distance,
    compute_edr_distance,
    calculate_edr_distance,
    AutoencoderWeirdnessDetector,
    LocalOutlierFactorDetector,
    PyODLocalOutlierFactor,
    fit_pyod_local_outlier_factor,
    calculate_mahalanobis_distance,
    compute_mahalanobis_distance,
)
from people_analytics_toolkit.attribution import (
    logarithmic_mean,
    lmdi_rate_mix_decomposition,
    LeaveOneOutExpectedDifferential,
    compute_shap_interaction_matrix,
    calculate_shap_interaction_matrix,
    extract_shap_inflection_thresholds,
    calculate_retained_vs_terminated_shap_contributions,
    compute_retained_vs_terminated_shap_contributions,
    correlation_heatmap_df,
)
from people_analytics_toolkit.mobility import (
    CareerMovementEmbeddings,
    compute_role_similarity_matrix,
    get_role_similarity_matrix,
    calculate_role_similarity_matrix,
    calculate_time_in_position,
    compute_time_in_position,
    calculate_stagnation_index,
    compute_stagnation_index,
)
from people_analytics_toolkit.compensation import (
    calculate_salary_band_midpoint,
    compute_salary_band_midpoint,
    calculate_compa_ratio,
    compute_compa_ratio,
    calculate_range_penetration,
    compute_range_penetration,
    classify_pay_band_status,
    is_red_circled,
    is_green_circled,
    calculate_pay_equity_gap,
    compute_pay_equity_gap,
    median_gap,
    calculate_median_pay_gap,
    compute_median_pay_gap,
)
from people_analytics_toolkit.ona import (
    calculate_degree_centrality,
    compute_degree_centrality,
    calculate_closeness_centrality,
    compute_closeness_centrality,
    calculate_betweenness_centrality,
    compute_betweenness_centrality,
    calculate_eigenvector_centrality,
    compute_eigenvector_centrality,
    calculate_burt_constraint,
    compute_burt_constraint,
    calculate_euler_centrality,
    compute_euler_centrality,
    calculate_collaboration_overload,
    compute_collaboration_overload,
    simulate_attrition_contagion,
    compute_complete_ona_profile,
    calculate_complete_ona_profile,
    calculate_span_of_control,
    compute_span_of_control,
    evaluate_span_reorganization_shock,
)
from people_analytics_toolkit.equity import (
    OaxacaBlinderResult,
    DecompositionResult,
    oaxaca_blinder_decomposition,
    demographic_parity_difference,
    demographic_parity_ratio,
    equalized_odds_difference,
    ExponentiatedGradientFairness,
    calculate_individual_fairness_consistency,
    compute_individual_fairness_consistency,
)
from people_analytics_toolkit.prescriptive import (
    AIPWResult,
    aipw_estimator,
    synthetic_difference_in_differences,
    HonestCausalTree,
    CausalForestDML,
    qini_curve,
    area_under_uplift_curve,
    doubly_robust_uplift_eval,
    compute_synthetic_control_weights,
    calculate_synthetic_control_weights,
    build_synthetic_control_twin,
    build_multi_pilot_synthetic_controls,
    notears_linear,
    compute_directed_causal_edge_weights,
    calculate_directed_causal_edge_weights,
    diagnose_causal_confounding,
)
from people_analytics_toolkit.trajectories import (
    ContinuousTimeMarkovChain,
    generate_metapath_walks,
    Metapath2Vec,
    DynamicEntitySelfAttention,
)

__version__ = "0.1.0"

__all__ = [
    # Cardinality
    "BayesianTargetEncoder",
    "GroupedLOOZScore",
    # Memory & Smoothing
    "fractional_difference",
    "get_fractional_weights",
    "scan_fractional_differencing",
    "weighted_weeks_since",
    "calculate_ewma",
    "compute_ewma",
    "scan_ewma_spans",
    "calculate_ewms",
    "compute_ewms",
    "calculate_poisson_ewma",
    "compute_poisson_ewma",
    "ExponentialSmoothingResult",
    "SmoothingResult",
    "double_exponential_smoothing",
    "triple_exponential_smoothing",
    "HazardEmbeddings",
    "HazardEmbeddingTransformer",
    "fit_hazard_embeddings",
    "RollingMetricConfig",
    "compute_rolling_metrics",
    "calculate_rolling_metrics",
    "RollingMetricsPipeline",
    "singular_spectrum_analysis",
    "compute_svd_smoothed_baseline",
    "calculate_svd_smoothed_baseline",
    "SingularSpectrumAnalysis",
    "compute_lag_features",
    "calculate_lag_features",
    "compute_differencing_features",
    "calculate_differencing_features",
    "TemporalFeaturesPipeline",
    # Chaos & Contagion
    "calculate_shannon_entropy",
    "compute_shannon_entropy",
    "rolling_shannon_entropy",
    "GARCHVolatilityModel",
    "GARCHVolatility",
    "GARCHResult",
    "GARCHModelResult",
    "fit_garch_volatility",
    "rolling_garch_volatility",
    "HawkesProcessContagion",
    "WorkforceHMMRegimes",
    "WorkforceHMM",
    "fit_workforce_hmm_regimes",
    "calculate_bradford_score",
    "compute_bradford_score",
    "classify_bradford_risk",
    "calculate_bradford_factor",
    "compute_bradford_factor",
    # Anomalies & Sequences
    "calculate_kl_divergence",
    "compute_kl_divergence",
    "calculate_jensen_shannon_divergence",
    "compute_jensen_shannon_divergence",
    "compute_dtw_distance",
    "calculate_dtw_distance",
    "compute_lcss_distance",
    "calculate_lcss_distance",
    "compute_edr_distance",
    "calculate_edr_distance",
    "AutoencoderWeirdnessDetector",
    "LocalOutlierFactorDetector",
    "PyODLocalOutlierFactor",
    "fit_pyod_local_outlier_factor",
    "calculate_mahalanobis_distance",
    "compute_mahalanobis_distance",
    # Attribution & Decomposition
    "logarithmic_mean",
    "lmdi_rate_mix_decomposition",
    "LeaveOneOutExpectedDifferential",
    "compute_shap_interaction_matrix",
    "calculate_shap_interaction_matrix",
    "extract_shap_inflection_thresholds",
    "calculate_retained_vs_terminated_shap_contributions",
    "compute_retained_vs_terminated_shap_contributions",
    "correlation_heatmap_df",
    # Career Mobility & Promotion Stagnation
    "CareerMovementEmbeddings",
    "compute_role_similarity_matrix",
    "get_role_similarity_matrix",
    "calculate_role_similarity_matrix",
    "calculate_time_in_position",
    "compute_time_in_position",
    "calculate_stagnation_index",
    "compute_stagnation_index",
    # Compensation & Pay Equity
    "calculate_salary_band_midpoint",
    "compute_salary_band_midpoint",
    "calculate_compa_ratio",
    "compute_compa_ratio",
    "calculate_range_penetration",
    "compute_range_penetration",
    "classify_pay_band_status",
    "is_red_circled",
    "is_green_circled",
    "calculate_pay_equity_gap",
    "compute_pay_equity_gap",
    "median_gap",
    "calculate_median_pay_gap",
    "compute_median_pay_gap",
    # Organizational Network Analysis (ONA) & Structural Hierarchy
    "calculate_degree_centrality",
    "compute_degree_centrality",
    "calculate_closeness_centrality",
    "compute_closeness_centrality",
    "calculate_betweenness_centrality",
    "compute_betweenness_centrality",
    "calculate_eigenvector_centrality",
    "compute_eigenvector_centrality",
    "calculate_burt_constraint",
    "compute_burt_constraint",
    "calculate_euler_centrality",
    "compute_euler_centrality",
    "calculate_collaboration_overload",
    "compute_collaboration_overload",
    "simulate_attrition_contagion",
    "compute_complete_ona_profile",
    "calculate_complete_ona_profile",
    "calculate_span_of_control",
    "compute_span_of_control",
    "evaluate_span_reorganization_shock",
    # Algorithmic Equity & Fairness
    "OaxacaBlinderResult",
    "DecompositionResult",
    "oaxaca_blinder_decomposition",
    "demographic_parity_difference",
    "demographic_parity_ratio",
    "equalized_odds_difference",
    "ExponentiatedGradientFairness",
    "calculate_individual_fairness_consistency",
    "compute_individual_fairness_consistency",
    # Prescriptive Interventions & Causal Inference
    "AIPWResult",
    "aipw_estimator",
    "synthetic_difference_in_differences",
    "HonestCausalTree",
    "CausalForestDML",
    "qini_curve",
    "area_under_uplift_curve",
    "doubly_robust_uplift_eval",
    "compute_synthetic_control_weights",
    "calculate_synthetic_control_weights",
    "build_synthetic_control_twin",
    "build_multi_pilot_synthetic_controls",
    "notears_linear",
    "compute_directed_causal_edge_weights",
    "calculate_directed_causal_edge_weights",
    "diagnose_causal_confounding",
    # Continuous-Time Trajectories & Heterogeneous Graphs
    "ContinuousTimeMarkovChain",
    "generate_metapath_walks",
    "Metapath2Vec",
    "DynamicEntitySelfAttention",
    # Deprecation Utilities
    "deprecated",
    "deprecated_alias",
]



